// services/docx.js
const {
  Document, Packer, Paragraph, TextRun,
  HeadingLevel, BorderStyle, AlignmentType,
} = require("docx");

const THEME_COLORS = {
  midnight: "1E2761", coral: "F96167",
  forest: "2C5F2D", ocean: "065A82", berry: "6D2E46",
};

async function generateDOCX(deckData, formData, themeName = "midnight") {
  const primaryColor = THEME_COLORS[themeName] || "1E2761";
  const op = deckData.onePager;

  const heading = (text) =>
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      spacing: { before: 300, after: 120 },
      children: [new TextRun({ text, bold: true, size: 26, color: primaryColor })],
    });

  const body = (text) =>
    new Paragraph({
      spacing: { after: 120 },
      children: [new TextRun({ text, size: 22, color: "333333" })],
    });

  const divider = () =>
    new Paragraph({
      spacing: { before: 160, after: 160 },
      border: { bottom: { style: BorderStyle.SINGLE, size: 4, color: "DDDDDD" } },
      children: [],
    });

  const doc = new Document({
    sections: [{
      properties: {
        page: {
          size: { width: 12240, height: 15840 },
          margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 },
        },
      },
      children: [
        // Company name
        new Paragraph({
          spacing: { after: 120 },
          children: [
            new TextRun({ text: formData.startupName, bold: true, size: 56, color: primaryColor }),
          ],
        }),
        // Headline
        new Paragraph({
          spacing: { after: 80 },
          children: [new TextRun({ text: op.headline, bold: true, size: 28, color: "222222" })],
        }),
        // Subheadline
        new Paragraph({
          spacing: { after: 300 },
          children: [new TextRun({ text: op.subheadline, size: 22, color: "666666", italics: true })],
        }),

        divider(),

        heading("The Problem"),
        body(op.problemStatement),

        heading("Our Solution"),
        body(op.solutionStatement),

        heading("Market Opportunity"),
        body(op.marketOpportunity),

        heading("Traction & Validation"),
        body(op.tractionHighlights),

        heading("Our Edge"),
        body(deckData.competitiveAdvantage),
        body(deckData.whyNow),

        heading("The Team"),
        body(op.teamStatement),

        heading("The Ask"),
        body(op.theAsk),

        divider(),

        // Footer
        new Paragraph({
          spacing: { before: 200 },
          children: [
            new TextRun({ text: op.contactLine + "  ·  Confidential  ·  Generated by DeckAI", size: 18, color: "AAAAAA" }),
          ],
        }),
      ],
    }],
  });

  const buf = await Packer.toBuffer(doc);
  return buf;
}

module.exports = { generateDOCX };
